
name: 'regu_sense_dbt'
version: '1.0.0'
config-version: 2

profile: 'regu_sense'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:         # 
  - "target"
  - "dbt_packages"
models:
  regu_sense_dbt:
    gold:
      materialized: table
      +pre-hook: "{{ log('Building ' ~ this.identifier ~ ' table', info=true) }}"
    staging:
      materialized: view
